# Inserts a blank line between shell prompts
add_newline = true

format = """
$directory\
$git_branch\
$git_status\
$fill\
$nodejs\
$aws\
$kubernetes\
$line_break\
$character
"""

palette = "catppuccin_macchiato"

[fill]
symbol = " "

[character]
success_symbol = "[[>](green)](peach)"
error_symbol = "[[x](red)](peach)"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[directory]
style = "lavender"
truncation_length = 4

[git_branch]
style = "mauve"

[git_status]
style = "maroon"

[nodejs]
format = "[js](bold green) [$version]($style) | "
version_format = "${raw}"
style = "teal"

[aws]
format = "[aws](bold yellow) [$profile $region]($style) | "
style = "peach"
[aws.region_aliases]
us-east-1 = "use1"
us-west-2 = "usw2"

[kubernetes]
format = "[k8s](bold sapphire) [$context $namespace]($style)"
style = "blue"
disabled = false

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"
